version: '3.7'
services:
  coredns:
    hostname: coredns_host
    container_name: coredns
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/coredns/ssl/certs:/etc/ssl/certs
      - ./Corefile:/Corefile
    ports:
      - "443:8443"
      - "53:8853"
      - "53:8853/udp"
    networks:
      - pnsdns
    restart: always

networks:
  pnsdns: